language: dart
sudo: false
dart:
 - dev
 - stable
 - 1.23.0
 - 1.22.1
cache:
 directories:
   - $HOME/.pub-cache
dart_task:
 - test: --platform vm -x content-shell -x chrome -x firefox -x dartium -x phantomjs --timeout 4x
 - test: --platform dartium
   install_dartium: true
 - dartfmt
 - dartanalyzer
matrix:
  exclude:
    # Repo was formatted with 1.23.x SDK
    - dart: 1.22.1
      dart_task: dartfmt
